/**
 * Project Sentinel - Cloudflare Worker Entry Point
 * Purpose: Main entry point for Cloudflare Workers runtime
 * Dependencies: Astro SSR adapter, cron handler
 * Structural Role: Worker bootstrap and request routing
 */

// Import Astro SSR handler - this is generated by the Astro build
import server from "./server/entry.mjs";
import { scheduled as cronHandler } from "./cron";

export interface Env {
  DB: D1Database;
  STORAGE: R2Bucket;
  SESSION: KVNamespace;
  IMAGES: R2Bucket;
  STANDARD_SERVICE_FEE?: string;
  SESSION_COOKIE_NAME?: string;
  [key: string]: unknown;
}

// Export Astro's request handler
export default {
  fetch: server.fetch,
  
  // Export scheduled handler for cron triggers
  scheduled: cronHandler
};
